### ISSUE TITLE
Import abs2 from Base?

### ISSUE THREAD

**Issue by Cody-G** [JuliaDiff/HyperDualNumbers.jl#17]
It looks like since v1.1.0 `abs2` is no longer imported from Base.  Is there a reason for this?  Seems to be breaking some of our old code.

**Comment by goedman** [comment]
Yes, that’s indeed a bug. I replaced importall by a limited import and missed abs2.

Thank you for spotting it. I’ll try to fix it ASAP.

**Comment by Cody-G** [comment]
Great, thanks!  I can also make a PR if it's just exporting that one function.

**Comment by goedman** [comment]
Master (version 2.0, on Julia 0.7- only) is fixed. Will check if I can update version 1.1.0 as well.
