### ISSUE TITLE
Suggestion: make the code citable

### ISSUE THREAD

**Issue by briochemc** [JuliaDiff/HyperDualNumbers.jl#24]
Hi Rob,

The reason I have been using this package is to use it in a paper I am working on. Right now I can simply refer to the repo's URL, but it would be better if the repo had a DOI to refer to. I have never done this myself but GitHub has [guidelines for that](https://guides.github.com/activities/citable-code/). If you think this is a good idea, I will try to do it for this package! :)

Cheers!

**Comment by goedman** [comment]
Hi Benoit, absolutely! I just did make you an admin of the repo. It might take an extra step because JuliaDiff often adds a layer. But if you accept the admin request, maybe you can try to get a DOI. Otherwise I can do it. Seems just a few steps.

Best, Rob

**Comment by briochemc** [comment]
Hi Rob,

Yes I just saw that you added me as a collaborator — Thank you, it's an honor! :)
I'll have a look at the guidelines for the DOI now...

**Comment by briochemc** [comment]
OK I "toggled the automatic preservation" of the repository on Zenodo, and the next step is to create a release. Should I tag a v4.0.0 release? Maybe there are other things that need to be changed before?

**Comment by goedman** [comment]
Just noticed it! Yes, I'm perfectly ok to release v4.0.0. Let me quickly update the version field in Project.toml to reflect this version number. Although everybody says that field does nothing, I certainly have seen issues with it.

My next step is to create a list (as an issue) of outstanding items we want to fix (basically as per your PRs), like documentation, more testing, functions that dropped out, etc.

I'm assuming Zenodo will download a new copy for each new release. These days releasing a package update to METADATA takes typically less that 1 to 2 hours.

**Comment by goedman** [comment]
What is your timeframe for publication? Let's prioritize items to what you feel most important for the publication.

Version field update is done.

**Comment by briochemc** [comment]
> What is your timeframe for publication?

I don't think the paper will be ready before this DOI 😅

**Comment by goedman** [comment]
Hi Benoit, is it your intention to tag version 4.0.0 or would you prefer me to do it?

I think 4.0.0 is ok as it is (and folks can always go back using HyperDualNumbers@3.0.1).

For the next few weeks I will have to split my time between StatisticalRethinking and HyperDualNumbers, hence my question about your timeline.

**Comment by briochemc** [comment]
Hi Rob,

Oh I thought you were asking about the timeline because you wanted to make some revisions before releasing v4.0.0! I'll do it now since you are saying it's OK for you 😄 (I'll close this issue when the DOI is out there but I think this will be automatic)

**Comment by briochemc** [comment]
Actually I think I'll port the tests from DualNumbers first :)

**Comment by goedman** [comment]
Hi Benoit,

That’s great.

I have been struggling today with getting a docs framework up and running. It’s not finding the doc elements for some reason, but the skeleton is there.

I have also updated the test_symata.jl script to show the expressions as used in the symbolic_derivative_list.  I have moved the `include(“derivatives_list.jl”)` to HyperDualNumbers.jl. What is the intention of the `symbolic_derivatives() = symbolic_derivative_list` statement at the end derivatives_list.j? I’m asking because I was looking for a way to include the list in a nice format in the documentation.

Best,
Rob
goedman@icloud.com

**Comment by briochemc** [comment]
Hi Rob, 

the `symbolic_derivatives() = symbolic_derivative_list` was a copy-paste from `DualNumbers.jl` I think, where the point I assume was to export the function `symbolic_derivatives()` rather than the variable `symbolic_derivative_list`. 

I have been asking a few questions related to the issues here and other "todos" (asking on the Julia slack) and I was pointed to this nice work in progress from Jarett Revels: https://discourse.julialang.org/t/chainrules-replacing-diffrules-in-the-julia-ad-world/17608
I am not sure what to make of it yet (I feel like its out of my league when I read about all this) but it may be the way forward?

**Comment by goedman** [comment]
Hi Benoit,

Agreed, let’s for a while at least use your list and revisit this say in the spring of next year. 

ChainRules.jl looks very interesting. And indeed, I too consider myself a user of these kind of tools, not a developer! I had also read some updates on Cassette.jl in that context. 

Also of interest in [YASGuide](https://github.com/jrevels/YASGuide <https://github.com/jrevels/YASGuide>). I always struggle with that.

Rob J Goedman
goedman@icloud.com

**Comment by goedman** [comment]
Hi Benoit,

Finally, the doc setup is fixed now. The coverage stuff is updated (jumped to 64%). The README layout is better.

I really like how you ported the DualNumber tests to HyperDualNumbers. Very clean.

How far do you think we should go with the docs? If we want to document the examples we should probably switch to Literate.jl, particularly is we would like to generate notebooks from the examples.

If we want to primarily focus on REPL docs we can just flesh out the current place holders for Hyper(), eps1, etc.

Best,
Rob

**Comment by briochemc** [comment]
Hi Rob,

Nice work!

Note that I can see the "dev" doc but I can't see the "stable" doc right now (404 when I click on the "stable" badge). 

I haven't had time to really dig into Literate.jl, so I am unsure how we should use it. Is there a package out there using Literate.jl to generate both the docs and notebooks (that you had in mind)? Or did you have a plan to structure it?

**Comment by goedman** [comment]
Hi Benoit,

“stable” will show up once we do a new release, so in our case “stable” will point to v4.0.0.

With Literate.jl, good examples are DynamicHMCExamples.jl and JuaFEM.jl. StatisticalRethinking.jl is “my” test ground, but not quite there. Basically I defined .jl scripts in subdirectories of the chapters directory  (00, 02, 03, …) and I use Literate to generate the actual snippets referred to in the book and at the same time generate .md docs and notebooks from the scripts in chapters.

We can decide later if this is useful for HyperDualNumbers.

Rob J Goedman
goedman@icloud.com
