### ISSUE TITLE
New version HyperDualNumbers.jl

### ISSUE THREAD

**Issue by goedman** [JuliaDiff/HyperDualNumbers.jl#30]
@JuliaRegistrator `register()`

**Comment by goedman** [comment]
@JuliaRegistrator `register()`

**Comment by goedman** [comment]
@JuliaRegistrator `register()`

**Comment by briochemc** [comment]
I think I can close this, but please reopen if I missed something :)

**Comment by goedman** [comment]
Thank you, I'll keep my eyes open if I updated TagBot. I did it for quite a few packages the last couple of days, not sure about HyperDualNumbers.
