### ISSUE TITLE
missing equivalence of Dual{T}(x::ReComp) where T<:ReComp = Dual{T}(T(x), zero(T)) 

### ISSUE THREAD

**Issue by githubtomtom** [JuliaDiff/HyperDualNumbers.jl#39]
line 9 in `dual.jl` see:
```
Dual{T}(x::ReComp) where T<:ReComp = Dual{T}(T(x), zero(T))
```

but it's missing the corresponding code in `hyperdual.jl`. It causes error like:
```
julia> Hyper{F64}(1f2)
ERROR: MethodError: no method matching Hyper{Float64}(::Float32)
```

the following code is suggested to add:
```
Hyper{T}(x::ReComp) where T<:ReComp = (z = zero(T); Hyper{T}(T(x), z, z, z) )
```

**Comment by briochemc** [comment]
Do you want to try and submit a PR? Add this line, a test for it, and increment the last digit of the version number in the Project.toml?

**Comment by githubtomtom** [comment]
I wanted and I tried ... turns out failed ... I always stuck in dealing with GitHub >.<
