### ISSUE TITLE
Sums derivatives for more than one argument.

### ISSUE THREAD

**Issue by z-m-k** [JuliaDiff/HyperDualNumbers.jl#9]
The result sums over all eps1/eps2/eps1eps2:

```
f(x)=x[1]^2+x[1]*x[2]^2
f(hyper(0.5, 1.0, 1.0, 0.0), hyper(5.1, 1.0, 1.0, 0.0))
```

This returns:

```
13.254999999999999 + 32.11ϵ1 + 32.11ϵ2 + 23.4ϵ1ϵ2
```

Where 32.11 is 27.01+5.1 which are slopes wrt. to each argument.

**Comment by goedman** [comment]
Hi @z-m-k ,

Thanks for your comment/observation. Not sure vectors were/are supported in the current implementation.

Just for completeness, on my system I get:

julia> using HyperDualNumbers

julia> f(x)=x[1]^2+x[1]*x[2]^2
f (generic function with 1 method)

julia> f(hyper(0.5, 1.0, 1.0, 0.0), hyper(5.1, 1.0, 1.0, 0.0))
ERROR: `f` has no method matching f(::Hyper{Float64}, ::Hyper{Float64})

I get your answer:

julia> f([hyper(0.5, 1.0, 1.0, 0.0), hyper(5.1, 1.0, 1.0, 0.0)])
13.254999999999999 + 32.11ϵ1 + 32.11ϵ2 + 23.4ϵ1ϵ2

Your observation is certainly very interesting (and new to me, clearly I lack the required mathematical skills to further this package). Is your comment intended as 'just' a (useful) comment or had you expected HyperDualNumbers to decompose ϵ1, etc.?

**Comment by goretkin** [comment]
This is how (hyper) dual numbers work. These number systems are useful for doing forward-mode auto-differentiation: taking the derivative of a function f: R^n -> R requires n evaluations. The mixing of the components is inherent to how (hyper) dual numbers work.

This same mixing also allows you take directional derivatives directly.

**Comment by goedman** [comment]
Thanks @goretkin !
